### ISSUE TITLE
Better Way to Deal with No Data Pixels

### ISSUE THREAD

**Issue by bcoltin** [nasa/delta#12]
What do we do now? It doesn't seem to be working great. Pixels in the middle of the image are being incorrectly classified as nodata.

**Comment by ScottMcMichael** [comment]
We have a filter to discard chunks where the label is equal to the label nodata value.  If you send me the test case where it is not working I can take a look at it.

**Comment by furlong-cmu** [comment]
I think the problem might be that we have a no-data value, which we use to eliminate all examples of nodata inputs.
But then we let the network predict the nodata value in the class outputs. 

Possible courses of action:
1. Modify the cost function to have high penalty for predicting nodata when there is data.
2. Automatically exclude the no-data value from predictions altogether, i.e. go in and re-label everything so they are in the set [0, 1, 2, num_classes -1]
3. Automatically label any no-data values with the second-highest class value. Being able to do this hinges on filtering out the nodata periphery in the images from the input values alone, otherwise we won't know when to reject a nodata output.

**Comment by bcoltin** [comment]
I think option 2 is the best personally. I've been meaning for a while to let you configure the different classes in the configuration files: names for things like the confusion matrix, pixel values so you don't have to use 0, 1, 2, 3, and display colors for the classification tools. I can start working on this.

**Comment by bcoltin** [comment]
This breaks backwards compatability. "classes" has been moved from train -> network to dataset in the config since it is also used in classification. You can use the number of classes like before or a more descriptive version.
